### ISSUE TITLE
页眉中数字和字母如何改成正体？

### ISSUE THREAD

**Issue by DXSHAN-NEU** [sci-m-wang/NEU-Thesis#1]
十分感谢学长的分享，请问页眉中数字和字母如何改成正体？

**Comment by sci-m-wang** [comment]
我不太清楚你说的正体是什么，一般英文字母和数字都要Times New Roman。如果你想修改的话，可以到artratex.sty中的Language Setting部分进行修改。

**Comment by sci-m-wang** [comment]
已经修改，下载Style中的文件并替换即可。
