### ISSUE TITLE
如何在该环境下添加数学环境

### ISSUE THREAD

**Issue by BitBute01** [sci-m-wang/NEU-Thesis#4]
\newtheorem{remark}{注解}
\newtheorem{assumption}{假设}
\newtheorem{theorem}{{定理}} 
\newtheorem{proposition}{{命题}} 
\newtheorem{lemma}{{引理}} 
\newtheorem{corollary}{{推论}}[theorem] 
\newtheorem{definition}{{定义}} 
\newtheorem{example}{{例}} 

添加这些命令，编译无法通过
![image](https://github.com/user-attachments/assets/297c7622-3f8e-4a52-93f7-e71c0c3b038c)
![image](https://github.com/user-attachments/assets/81337def-72fd-44fb-9af1-7ba5667cc8d1)

**Comment by sci-m-wang** [comment]
新的包和环境需要在sty文件中引入和定义
