### ISSUE TITLE
中文题目过长换行无法对齐的问题？

### ISSUE THREAD

**Issue by hbzjt2012** [sci-m-wang/NEU-Thesis#5]
请问在首页的中文题目过长，换行后无法对齐的问题该如何解决？

**Comment by sci-m-wang** [comment]
定位到`neuthesis.cls`这个文件的270行左右，也就是`\makereviewcover`这个方法的定义中，将`{\neu@value@title}`改成`\parbox[t]{0.73\textwidth}{\neu@value@title}`，就可以实现悬挂缩进的效果了。
